### ISSUE TITLE
https instead of git for unprivileged

### ISSUE THREAD

**Issue by colindaven** [DecodeGenetics/graphtyper#1]
Hi, 

interesting sounding tool.

Installation

The https clone will likely work better than the git:// URL for most unprivileged users.

-Works fine
 git clone --recursive https://github.com/DecodeGenetics/graphtyper.git
Cloning into 'graphtyper'...

Error:

git clone --recursive git@github.com:DecodeGenetics/graphtyper.git graphtyper && cd graphtyper
Cloning into 'graphtyper'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

cheers

**Comment by hannespetur** [comment]
Hey Colin. Thank you for your helpful comment. I have updated the README accordingly.

Hannes
