### ISSUE TITLE
HLA Typing

### ISSUE THREAD

**Issue by malmarri** [DecodeGenetics/graphtyper#105]
Hi,

1) I would like to use the genotype_hla command that was introduced in release 2.7.1. The release note states:

**Added new experimental subcommand "genotype_hla" for MHC/HLA genotyping (detailed instruction on how to run this will be added to the wiki).**

But I cannot find a wiki, is it available?

2) The graphtyper publications states that  "HLA reference alleles were fetched from the IPD-IMGT/HLA database... Each HLA allele corresponds to a path in Graphtyper’s graph. A graph is constructed for each gene and the alleles are called
based on the paths the reads align to."

Is this graph already within the release? or would I need to download the HLA alleles and construct the graph myself?

Thank you

**Comment by hannespetur** [comment]
Hey, sorry for your troubles, I had forgotten to make the wiki page for the HLA typing.

But now it's here:
https://github.com/DecodeGenetics/graphtyper/wiki/HLA-genotyping

The HLA graphs will be constructed from the VCFs in the HLA_data.tar.gz archive.


Best,
Hannes

**Comment by malmarri** [comment]
Thank you!
