### ISSUE TITLE
call and genotype Sv with population 

### ISSUE THREAD

**Issue by zhoudreames** [DecodeGenetics/graphtyper#111]
I want to call and genotype SV with population-level by using manta-svimmer-graphtype workflow, but I don't know how to gain the tutorial of the whole process,  Can you provide me with tutorials and more details for it ？ thanks~

**Comment by hannespetur** [comment]
Hi, the github wiki page should be a good place to start

https://github.com/DecodeGenetics/graphtyper/wiki/User-guide#structural-variants-svs
