### ISSUE TITLE
how to gain the sequence information

### ISSUE THREAD

**Issue by zhoudreames** [DecodeGenetics/graphtyper#112]
I get the vcf files with graphtyper, but the column of REF and ALT doesn't contain sequence information. For example:
![image](https://user-images.githubusercontent.com/54714639/180459313-03a9d85f-fdb8-4358-80ca-8c5e30e11a51.png)
but I want to gain such format, the REF and ALT  shown as G and GAAAAGTAAACTTGGGAGTTCCCAT...., how to gain such 
format ？ thanks~
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT
chr2    8005860 chr2:8005860:DG G GAAAAGTAAACTTGGGAGTTCCCATT.....
```

**Comment by hannespetur** [comment]
Hi, sorry for the late response, I have been on a long leave

It is not possible to output the SV calls in the format, unfortunately. Maybe if your input VCF is using that format you could modify the VCF afterwards with the INFO/OLD_VARIANT_ID to retrieve the correct sequence from the input.
