### ISSUE TITLE
arm64 installtion

### ISSUE THREAD

**Issue by xiaopangjun666** [DecodeGenetics/graphtyper#117]
Recently, v2.7.4 was installed under arm64 and the clang compiler was used,
FLAGS="-march=armv8.2-a -mcpu=tsv110"; CFLAGS=$FLAGS CXXFLAGS=$FLAGS \
cmake -DCMAKE_INSTALL_PREFIX=/root/install/graphtyper \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_CXX_COMPILER=clang++ \ 
../
 but the following errors were encountered when i input make：
Scanning dependencies of target project_paw
[  1%] Creating directories for 'project_paw'
[  2%] No download step for 'project_paw'
[  3%] No patch step for 'project_paw'
[  4%] No update step for 'project_paw'
[  5%] No configure step for 'project_paw'
[  6%] Performing build step for 'project_paw'
-- The CXX compiler identification is Clang 12.0.0
-- Check for working CXX compiler: /usr/local221017224509/bisheng-compiler-2.1.0/bin/clang++
-- Check for working CXX compiler: /usr/local221017224509/bisheng-compiler-2.1.0/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CAN_COMPILE_X86_SSE2
-- Performing Test CAN_COMPILE_X86_SSE2 - Failed
-- Performing Test CAN_COMPILE_X86_SSE3
-- Performing Test CAN_COMPILE_X86_SSE3 - Failed
-- Performing Test CAN_COMPILE_X86_SSSE3
-- Performing Test CAN_COMPILE_X86_SSSE3 - Failed
-- Performing Test CAN_COMPILE_X86_SSE4_1
-- Performing Test CAN_COMPILE_X86_SSE4_1 - Failed
-- Performing Test CAN_COMPILE_X86_POPCNT_INSN
-- Performing Test CAN_COMPILE_X86_POPCNT_INSN - Failed
-- Performing Test CAN_COMPILE_X86_AVX
-- Performing Test CAN_COMPILE_X86_AVX - Failed
-- Performing Test CAN_COMPILE_X86_AVX2
-- Performing Test CAN_COMPILE_X86_AVX2 - Failed
-- Performing Test CAN_COMPILE_X86_FMA3
-- Performing Test CAN_COMPILE_X86_FMA3 - Failed
-- Performing Test CAN_COMPILE_X86_FMA4
-- Performing Test CAN_COMPILE_X86_FMA4 - Failed
-- Performing Test CAN_COMPILE_X86_XOP
-- Performing Test CAN_COMPILE_X86_XOP - Failed
-- Performing Test CAN_COMPILE_X86_AVX512F
-- Performing Test CAN_COMPILE_X86_AVX512F - Failed
-- Performing Test CAN_COMPILE_X86_AVX512BW
-- Performing Test CAN_COMPILE_X86_AVX512BW - Failed
-- Performing Test CAN_COMPILE_X86_AVX512DQ
-- Performing Test CAN_COMPILE_X86_AVX512DQ - Failed
-- Performing Test CAN_COMPILE_X86_AVX512VL
-- Performing Test CAN_COMPILE_X86_AVX512VL - Failed
-- Performing Test CAN_COMPILE_ARM_NEON
-- Performing Test CAN_COMPILE_ARM_NEON - Success
-- Performing Test CAN_COMPILE_ARM64_NEON
-- Performing Test CAN_COMPILE_ARM64_NEON - Success
-- Performing Test CAN_COMPILE_MIPS_MSA
-- Performing Test CAN_COMPILE_MIPS_MSA - Failed
-- Performing Test CAN_COMPILE_POWER_ALTIVEC
-- Performing Test CAN_COMPILE_POWER_ALTIVEC - Failed
-- Performing Test CAN_COMPILE_POWER_VSX_206
-- Performing Test CAN_COMPILE_POWER_VSX_206 - Failed
-- Performing Test CAN_COMPILE_POWER_VSX_207
-- Performing Test CAN_COMPILE_POWER_VSX_207 - Failed
-- Performing Test CAN_RUN_X86_SSE2
-- Performing Test CAN_RUN_X86_SSE2 - Failed
-- Performing Test CAN_RUN_X86_SSE3
-- Performing Test CAN_RUN_X86_SSE3 - Failed
-- Performing Test CAN_RUN_X86_SSSE3
-- Performing Test CAN_RUN_X86_SSSE3 - Failed
-- Performing Test CAN_RUN_X86_SSE4_1
-- Performing Test CAN_RUN_X86_SSE4_1 - Failed
-- Performing Test CAN_RUN_X86_POPCNT_INSN
-- Performing Test CAN_RUN_X86_POPCNT_INSN - Failed
-- Performing Test CAN_RUN_X86_AVX
-- Performing Test CAN_RUN_X86_AVX - Failed
-- Performing Test CAN_RUN_X86_AVX2
-- Performing Test CAN_RUN_X86_AVX2 - Failed
-- Performing Test CAN_RUN_X86_FMA3
-- Performing Test CAN_RUN_X86_FMA3 - Failed
-- Performing Test CAN_RUN_X86_FMA4
-- Performing Test CAN_RUN_X86_FMA4 - Failed
-- Performing Test CAN_RUN_X86_XOP
-- Performing Test CAN_RUN_X86_XOP - Failed
-- Performing Test CAN_RUN_X86_AVX512F
-- Performing Test CAN_RUN_X86_AVX512F - Failed
-- Performing Test CAN_RUN_X86_AVX512BW
-- Performing Test CAN_RUN_X86_AVX512BW - Failed
-- Performing Test CAN_RUN_X86_AVX512DQ
-- Performing Test CAN_RUN_X86_AVX512DQ - Failed
-- Performing Test CAN_RUN_X86_AVX512VL
-- Performing Test CAN_RUN_X86_AVX512VL - Failed
-- Performing Test CAN_RUN_ARM_NEON
-- Performing Test CAN_RUN_ARM_NEON - Success
-- Performing Test CAN_RUN_ARM64_NEON
-- Performing Test CAN_RUN_ARM64_NEON - Failed
-- Performing Test CAN_RUN_MIPS_MSA
-- Performing Test CAN_RUN_MIPS_MSA - Failed
-- Performing Test CAN_RUN_POWER_ALTIVEC
-- Performing Test CAN_RUN_POWER_ALTIVEC - Failed
-- Performing Test CAN_RUN_POWER_VSX_206
-- Performing Test CAN_RUN_POWER_VSX_206 - Failed
-- Performing Test CAN_RUN_POWER_VSX_207
-- Performing Test CAN_RUN_POWER_VSX_207 - Failed
-- Compilable archs are: NONE_NULL;ARM_NEON;ARM_NEON_FLT_SP;ARM64_NEON
-- Runnable archs are: NONE_NULL;ARM_NEON;ARM_NEON_FLT_SP
-- CMAKE_BUILD_TYPE is set to RELEASE
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX14
-- Performing Test COMPILER_SUPPORTS_CXX14 - Success
-- Performing Test COMPILER_SUPPORTS_CXX17
-- Performing Test COMPILER_SUPPORTS_CXX17 - Success
-- clang-tidy not found. Code diagnostics and statis analyzes will be skipped.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/graphtyper-2.7.4/release-build/paw
[  6%] Generating src/align_simdpp_-x86_avx512bw-x86_avx512dq-x86_avx512f-x86_avx512vl-x86_popcnt.cpp
[ 12%] Generating src/align_simdpp_-null.cpp
[ 18%] Generating src/align_simdpp_-x86_sse2.cpp
[ 25%] Generating src/align_simdpp_-x86_sse4_1.cpp
[ 31%] Generating src/align_simdpp_-x86_popcnt-x86_sse4_1.cpp
[ 37%] Generating src/align_simdpp_-x86_avx-x86_popcnt.cpp
[ 43%] Generating src/align_simdpp_-x86_avx2-x86_popcnt.cpp
Scanning dependencies of target static
[ 50%] Building CXX object CMakeFiles/static.dir/src/paw.cpp.o
In file included from /root/graphtyper-2.7.4/paw/src/paw.cpp:2:
In file included from /root/graphtyper-2.7.4/paw/include/paw.hpp:9:
In file included from /root/graphtyper-2.7.4/paw/include/paw/align.hpp:5:
In file included from /root/graphtyper-2.7.4/paw/include/paw/align/alignment_cache.hpp:13:
/root/graphtyper-2.7.4/paw/include/paw/align/event.hpp:103:21: warning: lambda capture 's' is not used [-Wunused-lambda-capture]
    [&pos, &pos_q, &s, &s1, &s2, &edit_script, &ref, is_normalize, is_trim_indel_on_ends]() -> void
                 ~~~^
1 warning generated.
[ 56%] Building CXX object CMakeFiles/static.dir/src/align_simdpp_-null.cpp.o
In file included from /root/graphtyper-2.7.4/release-build/paw/src/align_simdpp_-null.cpp:10:
In file included from /root/graphtyper-2.7.4/paw/include/paw/align/alignment_options.hpp:10:
In file included from /root/graphtyper-2.7.4/paw/include/paw/align/alignment_cache.hpp:13:
/root/graphtyper-2.7.4/paw/include/paw/align/event.hpp:103:21: warning: lambda capture 's' is not used [-Wunused-lambda-capture]
    [&pos, &pos_q, &s, &s1, &s2, &edit_script, &ref, is_normalize, is_trim_indel_on_ends]() -> void
                 ~~~^
1 warning generated.
[ 62%] Building CXX object CMakeFiles/static.dir/src/align_simdpp_-x86_sse2.cpp.o
clang-12: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
In file included from /root/graphtyper-2.7.4/release-build/paw/src/align_simdpp_-x86_sse2.cpp:7:
In file included from /root/graphtyper-2.7.4/paw/include/simdpp/simd.h:14:
In file included from /root/graphtyper-2.7.4/paw/include/simdpp/setup_arch.h:264:
In file included from /usr/local221017224509/bisheng-compiler-2.1.0/lib/clang/12.0.0/include/xmmintrin.h:13:
/usr/local221017224509/bisheng-compiler-2.1.0/lib/clang/12.0.0/include/mmintrin.h:33:5: fatal error: use of undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/usr/local221017224509/bisheng-compiler-2.1.0/lib/clang/12.0.0/include/mmintrin.h:33:5: note: '__builtin_isless' declared here
1 error generated.
make[6]: *** [CMakeFiles/static.dir/build.make:117: CMakeFiles/static.dir/src/align_simdpp_-x86_sse2.cpp.o] Error 1
make[5]: *** [CMakeFiles/Makefile2:110: CMakeFiles/static.dir/all] Error 2
make[4]: *** [CMakeFiles/Makefile2:117: CMakeFiles/static.dir/rule] Error 2
make[3]: *** [Makefile:188: static] Error 2
make[2]: *** [CMakeFiles/project_paw.dir/build.make:112: paw/src/project_paw-stamp/project_paw-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/project_paw.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
@pmelsted @GuillaumeHolley @h-2  could you provide help for me？thanks！

**Comment by h-2** [comment]
I think the paw-library (required by Graphtyper) only supports 64bit Intel/AMD platforms.
