### ISSUE TITLE
A few errors in my bams raise a std::exit(1);, how can I modify the C++ code to skip the read(s) ?

### ISSUE THREAD

**Issue by lindenb** [DecodeGenetics/graphtyper#125]
Hi,
thank you for Graphtyper.

As I said in the title, I've got a few reads with an error (both reads are FIRST_IN_PAIR) which raises the exception in https://github.com/DecodeGenetics/graphtyper/blob/e20753183951b50744c43b1957249e06a8e9bd4b/src/utilities/hts_parallel_reader.cpp#L306

instead of re-writting all my bams, is there anything I can do in the code to skip the reads, to skip the error ? e.g: adding a `return` statement ? anything else ?

Thank you for any advice

**Comment by hannespetur** [comment]
Hi,

I'd think it would work ok to replace std::exit(1) with return. It will lead to some strangeness because the order of the input will affect the results. For example if the order is:

```
READ1/1
READ1/1 <= ERROR! A duplicate, ignore it
READ2/2 <= OK! Pair found!
READ2/2 <= Will wait in the hash map with no mate until all reads have been written
```

Then only one read pair is found but two if the order is 

```
READ1/1
READ1/2 <= OK! Pair found!
READ1/1
READ1/2 <= OK! Pair found!
```

I am not sure which of those behaviors your want to happen, but getting a mix of both is probably not what you want. But if it is only happening in very rare cases it might not be important.


Best,
Hannes

**Comment by lindenb** [comment]
I'll try this . Thank you very much for your answer !

**Comment by realgoldace** [comment]
I modified the code by this :
if ((geno_paths.first.flags & IS_FIRST_IN_PAIR) == (find_it->second.first.flags & IS_FIRST_IN_PAIR))
    {
      print_log(log_severity::warning, 
                __HERE__,
                "Invalid pair flags for read=",
                read_name,
                ". Both marked as ",
                ((geno_paths.first.flags & IS_FIRST_IN_PAIR) ? "first" : "second"),
                "-in-pair. Discarding both reads.");
      

      map_gpaths.erase(find_it);
      return;  
    }
  Just discard the reads, and it seems to work fine

**Comment by realgoldace** [comment]
To overcome the issue :
READ1/1
READ1/1 <= ERROR! A duplicate, ignore it
READ2/2 <= OK! Pair found!
READ2/2 <= Will wait in the hash map with no mate until all reads have been written
I modifed the code to this, it seems to run normally, and just skips the error and coverts the the abnormal paired reads to unpaired reads
if ((geno_paths.first.flags & IS_FIRST_IN_PAIR) == (find_it->second.first.flags & IS_FIRST_IN_PAIR))
    {

print_log(log_severity::warning,
         __HERE__,
         "Sample index ", sample_i, ": Invalid pair ", read_name, 
         " (both ", ((geno_paths.first.flags & IS_FIRST_IN_PAIR) ? "FIRST" : "SECOND"), 
         "). Converting both to unpaired.");
      

      if (GenotypePaths* prev_selected = update_unpaired_read_paths(find_it->second, hts_rec.record))
      {
        writer.update_haplotype_scores_geno(*prev_selected, sample_i, primers);
      }
      

      if (GenotypePaths* current_selected = update_unpaired_read_paths(geno_paths, hts_rec.record))
      {
        writer.update_haplotype_scores_geno(*current_selected, sample_i, primers);
      }
      
      map_gpaths.erase(find_it);
      return;
    }
