### ISSUE TITLE
Should there be no commas in the subsequent processing of the graphtyper output file that describes the document?

### ISSUE THREAD

**Issue by jingydz** [DecodeGenetics/graphtyper#134]
https://github.com/DecodeGenetics/graphtyper/wiki/User-guide
$ echo chr{1..22} chrX | tr ' ' '\n' | while read chrom; do; if [[ ! -d results/${chrom} ]]; then continue; fi; find results/${chrom} -name "*.vcf.gz" | sort; done > vcf_file_list
![image](https://github.com/DecodeGenetics/graphtyper/assets/45711930/10070f5a-1580-4180-a3b2-58aaf1900e08)

Should there be no commas in the subsequent processing of the graphtyper output file that describes the document?

$ echo chr{1..22} chrX chrY chrM | tr ' ' '\n' | while read chrom; do; if [[ ! -d test.lst.genotype.vcf/${chrom} ]]; then continue; fi; find test.lst.genotype.vcf/${chrom} -name "*.vcf.gz" | sort; done >test.lst.genotype.combine.vcf.lst
-bash: syntax error near unexpected token `;'

$ echo chr{1..22} chrX chrY chrM | tr ' ' '\n' | while read chrom; do if [[ ! -d test.lst.genotype.vcf/${chrom} ]]; then continue; fi; find test.lst.genotype.vcf/${chrom} -name "*.vcf.gz" | sort; done >test.lst.genotype.combine.vcf.lst

$ head -n 2 test.lst.genotype.combine.vcf.lst
test.lst.genotype.vcf/chr1/000000001-001000000.vcf.gz
test.lst.genotype.vcf/chr1/001000001-002000000.vcf.gz

**Comment by hannespetur** [comment]
You are right. I have fixed the command in the user guide. Thank you for reporting.
