### ISSUE TITLE
genotyping small variant error, result only contains vcf header!

### ISSUE THREAD

**Issue by tanger-code** [DecodeGenetics/graphtyper#135]
Hi,
I want to genotyping the chr21 using command:` graphtyper genotype GRCh38#chr21.fa --sam=chr21.sorted.bam --region=chr21`.
But there seems to be something wrong with it.  The result only contains header.
![image](https://github.com/DecodeGenetics/graphtyper/assets/74750242/5ea866bf-06e3-4c45-a492-113a18ad3a27)

Why does this happen？The ref GRCh38#chr21.fa file that I used contains 2 lines.

**Comment by hannespetur** [comment]
Hey, can you check if the contig names match in the FASTA and BAM are chr21? Also were there any log messages?

**Comment by tanger-code** [comment]
This is the first 100 lines of the BAM file：
[chr21_bam_head100.txt](https://github.com/DecodeGenetics/graphtyper/files/12883213/chr21_bam_head100.txt)
And this is the first 100 lines of the ref.fa file:
[GRCh38_chr21_head100_fa.txt](https://github.com/DecodeGenetics/graphtyper/files/12883262/GRCh38_chr21_head100_fa.txt)
The contig name is both chr21. And there is no error log for GraphTyper.

**Comment by hannespetur** [comment]
Sorry, graphtyper won't work with long read data.
