### ISSUE TITLE
sample order in the output VCFs

### ISSUE THREAD

**Issue by lindenb** [DecodeGenetics/graphtyper#136]
Hi graphtyper team,

I've been using `graphtyper genotype` with only-CRAM files:

```
 --sams=crams.list 
```

 but also with only-BAMS files, for the very same samples in the very same order.

```
 --sams=bams.list 
```

there was not difference with:

```
samtools samples < crams.list  | cut -f1
samtools samples < bams.list  | cut -f1
```

Nevertheless , I was surprised to see that the order of samples in the VCFs was not the same in both files (at the end, `bcftools concat` crashed). Could you please confirm that ?

Thank you !

**Comment by hannespetur** [comment]
Hello, yes I can confirm that graphtyper will read the BAM/CRAMs in the same order as in the input but will then determine the sample order based on their filename. We were having some I/O latencies issues in our large scale runs early on, so I implemented this so we could give each interval/region a BAM/CRAMs list in random order such that the I/O calls were better distributed while getting consistently the same sample order in the output VCF.

Here is the culprit
https://github.com/DecodeGenetics/graphtyper/blob/master/src/utilities/genotype.cpp#L395

As you see this can be turned off by specifying the `--no_sample_name_reordering` (an advanced option). But you'd probably not want to rerun, rather run `bcftools view -S<file_with_correct_sample_order>` to change the order.

sorry for the inconvenience

Best,
Hannes

**Comment by lindenb** [comment]
@hannespetur thanks for your answer ! I  was not crazy in the end !   :-)
