### ISSUE TITLE
Reads with name=dG both have IS_FIRST_IN_PAIR=0

### ISSUE THREAD

**Issue by tanger-code** [DecodeGenetics/graphtyper#137]
Hi.
I first map the paired end reads to `.vg` graph. Then use vg surject to convert the `.gam` file to `.bam` file. Then I use `graphtyper `to do genotyping. But there is an error: `Reads with name=dG both have IS_FIRST_IN_PAIR=0.`
Why does this happen?

**Comment by hannespetur** [comment]
Hey, graphtyper expects to find 2 reads with the same read name to form a read pair. One is expected to be marked as first-in-pair and other as second-in-pair. In this case graphtyper found two reads with name "dG" that are both marked as the second-in-pair so it cannot form the read pair.

Best,
Hannes
