### ISSUE TITLE
bioconda package

### ISSUE THREAD

**Issue by TorHou** [DecodeGenetics/graphtyper#22]
Hi there,

I am currently working on making graph genome tools more accessible for non-bioinformaticians, together with @AlexanderDilthey. We think that [bioconda](https://bioconda.github.io/) has gained a lot of support in the community, and so we would like to add a graphtyper package to that channel. Would you be interested in collaborating on this?

**Comment by TorHou** [comment]
For now I will probably just use the statically linked binary. I will try to build a conda package soon though.

**Comment by hannespetur** [comment]
graphtyper is now available on bioconda. https://bioconda.github.io/recipes/graphtyper/README.html

Thank you for the suggestion.

Best regards,
Hannes
