### ISSUE TITLE
Manta Inversion Split

### ISSUE THREAD

**Issue by malmarri** [DecodeGenetics/graphtyper#23]
Hi,

Congrats on your new paper and tool.

1) I would like to genotype SVs identified by Manta. In the new version of Manta (1.6), Inversions are reported as breakends by default. "For a simple reciprocal inversion, four breakends will be reported, and they shall share the same EVENT INFO tag". A script is supplied to convert these inversions into single inverted sequence as previous versions have. My question is should the inversions be converted to be used by graphtyper or is the new format fine.

2) If I only want to genotype SVs, do I need to include SNPs and indels in the graphs? Also, are crams supported?

Best wishes,
Mo

**Comment by hannespetur** [comment]
Hello, thank you. 

1. I wasn't aware they change the inversion format in Manta 1.6. So you should probably convert the inversions back to the old format. Our current plan is to support the Manta discovered SVs so I expect we will support the new format in a future release.
2. No, you can provide a VCF with SVs only. Though we have seen it helps to have SNPs/indels in the graph if they are in close proximity to SV breakpoint and on the same haplotype, but this isn't very common.

Best,
Hannes

**Comment by malmarri** [comment]
Thanks for the clarification.

**Comment by YiBenqiu** [comment]
> 1. I would like to genotype SVs identified by Manta. In the new version of Manta (1.6), Inversions are reported as breakends by default. "For a simple reciprocal inversion, four breakends will be reported, and they shall share the same EVENT INFO tag". A script is supplied to convert these inversions into single inverted sequence as previous versions have. My question is should the inversions be converted to be used by graphtyper or is the new format fine.

Is there an update on this issue? Or do we still need to convert?
