### ISSUE TITLE
make error "stdlib.h"

### ISSUE THREAD

**Issue by asylvz** [DecodeGenetics/graphtyper#31]
Hello,
I'm trying to make graphtyper, but I get the following error in ubuntu 18.04, although I believe I have all the dependencies installed. Do you have any idea? Am I missing something?

Thanks,
Arda

[ 44%] No install step for 'project_rocksdb'
[ 44%] Completed 'project_rocksdb'
[ 44%] Built target project_rocksdb
Scanning dependencies of target graphtyper_objects
[ 45%] Building CXX object src/CMakeFiles/graphtyper_objects.dir/graph/absolute_position.cpp.o
[ 48%] Building CXX object src/CMakeFiles/graphtyper_objects.dir/graph/constructor.cpp.o
[ 48%] Building CXX object src/CMakeFiles/graphtyper_objects.dir/graph/genomic_region.cpp.o
[ 48%] Building CXX object src/CMakeFiles/graphtyper_objects.dir/graph/genotype.cpp.o
In file included from /usr/include/c++/7/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /home/asoylev/apps/graphtyper/include/graphtyper/graph/absolute_position.hpp:3,
                 from /home/asoylev/apps/graphtyper/src/graph/absolute_position.cpp:4:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
src/CMakeFiles/graphtyper_objects.dir/build.make:62: recipe for target 'src/CMakeFiles/graphtyper_objects.dir/graph/absolute_position.cpp.o' failed
make[3]: *** [src/CMakeFiles/graphtyper_objects.dir/graph/absolute_position.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/7/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/istream:38,
                 from /usr/include/c++/7/sstream:38,
                 from /home/asoylev/apps/graphtyper/src/graph/constructor.cpp:2:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
src/CMakeFiles/graphtyper_objects.dir/build.make:86: recipe for target 'src/CMakeFiles/graphtyper_objects.dir/graph/constructor.cpp.o' failed
make[3]: *** [src/CMakeFiles/graphtyper_objects.dir/graph/constructor.cpp.o] Error 1
In file included from /usr/include/c++/7/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/ostream:38,
                 from /home/asoylev/apps/graphtyper/src/graph/genomic_region.cpp:1:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
src/CMakeFiles/graphtyper_objects.dir/build.make:110: recipe for target 'src/CMakeFiles/graphtyper_objects.dir/graph/genomic_region.cpp.o' failed
make[3]: *** [src/CMakeFiles/graphtyper_objects.dir/graph/genomic_region.cpp.o] Error 1
In file included from /usr/include/c++/7/ext/string_conversions.h:41:0,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/bits/locale_classes.h:40,
                 from /usr/include/c++/7/bits/ios_base.h:41,
                 from /usr/include/c++/7/ios:42,
                 from /usr/include/c++/7/ostream:38,
                 from /usr/include/boost/archive/binary_oarchive.hpp:19,
                 from /home/asoylev/apps/graphtyper/src/graph/genotype.cpp:3:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
src/CMakeFiles/graphtyper_objects.dir/build.make:134: recipe for target 'src/CMakeFiles/graphtyper_objects.dir/graph/genotype.cpp.o' failed
make[3]: *** [src/CMakeFiles/graphtyper_objects.dir/graph/genotype.cpp.o] Error 1
CMakeFiles/Makefile2:314: recipe for target 'src/CMakeFiles/graphtyper_objects.dir/all' failed
make[2]: *** [src/CMakeFiles/graphtyper_objects.dir/all] Error 2
CMakeFiles/Makefile2:367: recipe for target 'src/CMakeFiles/graphtyper.dir/rule' failed
make[1]: *** [src/CMakeFiles/graphtyper.dir/rule] Error 2
Makefile:266: recipe for target 'graphtyper' failed
make: *** [graphtyper] Error 2

**Comment by hannespetur** [comment]
Hello, can you change "-isystem" to "-I" in line 94 from CMakeLists.txt and then run make again.
 
Apparently, it's a problem to have the argument "-isystem /usr/include" in gcc but "-I /usr/include" is fine.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129


Best,
Hannes

**Comment by asylvz** [comment]
Thank you, that solved it. However, I now get this weird seg. fault (although those files are there):
**genotype_sv /mnt/compgen/inhouse/share/rg_annot/b37/human_g1k_v37.fasta /home/asoylev/benchmark/dnm.vcf.gz --sams /home/asoylev/benchmark/dataset/simulation/30x/simu30x.bam --region=1**

[E::hts_open_format] Failed to open file "" : No such file or directory
ERROR: Could not open BAM file  �BC�]V[h�E�$�vS)
[E::hts_open_format] Failed to open file "n`�~@����i�f3R���A��8;��֓��8�f �$��y��4��U=,[��;b�j��IW������q�J���q��@���@���E�)����}���5A�Z�M:"���6�j�g_��-�-�F=�;RLؖ1��F�ǧ�R)!a�#ܥ��~��{&5�,�B������Ӂߛ�a�����?�0�A`��%-ϡIӪ�a��qƫ*"���q�Rh)90b.ʔ4_N�ѼV"~y$ME��Ui검h�z��L)����k����">�ٰ"I�ط�T�$�j/�[�P���.�=��w`�`C򅁋�HA���zQ�h��n�E�n¼�$/C��u�Zԕ7d���CUz�" " : File name too long
ERROR: Could not open BAM file  n`�~@����i�f3R���A��8;��֓��8�f �$��y��4��U=,[��;b�j��IW������q�J���q��@���@���E�)����}���5A�Z�M:"���6�j�g_��-�-�F=�;RLؖ1��F�ǧ�R)!a�#ܥ��~��{&5�,�B������Ӂߛ�a�����?�0�A`��%-ϡIӪ�a��qƫ*"���q�Rh)90b.ʔ4_N�ѼV"~y$ME��Ui검h�z��L)����k����">�ٰ"I�ط�T�$�j/�[�P��S��r(lB���3���J+�0@LV�-����Hv<�;���.8�A{�t�t䔫��'����x>3C���4#Cj��)�B;�bv/��G���8�]e��.5�[�I�����?��<��i�P_j���|�;?�U��ׂa�꧋gPi5-�m��# ���T�I9邇жH4��Y��g[z
free(): corrupted unsorted chunks
Segmentation fault (core dumped)

**Comment by hannespetur** [comment]
Hello. You need to change "--sams" to "--sam" in your command. The --sams argument expects a list of SAM/BAM/CRAM files (one per line). 

Best,
Hannes

**Comment by asylvz** [comment]
Great, thank you. Lastly, is it possible to genotype the whole genome at once (instead of giving a region with --region) and create a single vcf at the end?

**Comment by hannespetur** [comment]
No sorry, you can't get a single VCF in the end for the whole genome. You will need to concatenate the VCFs using bcftools concat --naive / vt cat / graphtyper vcf_concatenate --no_sort to get one huge VCF.

**Comment by hannespetur** [comment]
I will close the issue since I believe has been solved. If not, feel free to reopen it or create a new issue if more problems arise.
