### ISSUE TITLE
genotype_sv on insertions

### ISSUE THREAD

**Issue by aakrosh** [DecodeGenetics/graphtyper#40]
Hello,
   I am running Graphtyper2 to genotype SVs that were discovered in another cohort. The VCF file from the discovery does not include the inserted sequence (it just uses the `<INS>` tag in the column for the alternate allele), though it does include the length of the insertion. Is it possible to use graphtyper to genotype such insertions without knowing the insertion sequence? 

Thanks,
--Aakrosh

**Comment by hannespetur** [comment]
Hi Aakrosh, no sorry it is not possible. For deletions and tandem duplications the SV length is enough but otherwise Graphtyper will need the sequence to put it in its graph. 

Best,
Hannes

**Comment by aakrosh** [comment]
Thank you for the prompt response.
