### ISSUE TITLE
Some variants missed in the genotype_sv results

### ISSUE THREAD

**Issue by biozzq** [DecodeGenetics/graphtyper#44]
Dear @hannespetur,

According to the previous post (https://github.com/DecodeGenetics/graphtyper/issues/42#issue-642729990),  I finished most of the processes. However, a few issues occurred to me during running `genotype_sv`. I ran `graphtyper genotype_sv` for each reference chromosome separately.

First, I found some variants presented in the candidate VCF file but missed in the genotype_sv results.

Second, I cannot find the log file when using the following command
`graphtyper genotype_sv ${ref} ${candidate.vcf.gz} --output=${out} --sams=${bamlist} --region=${chr} --threads=8 --log=log`

Third, as you mentioned in the previous post, we can require FT format field to be "PASS" to get a accurate set of variants and calls. However, I found that few variants can meet above conditions. Thus, I decided to filter by `PASS_ratio` using following command, and then change the GT to `./.` if its FT is `FAILN`.
`bcftools view -f "PASS" -i 'INFO/SVMODEL="AGGREGATED" && INFO/PASS_ratio>=0.9'`

Sincerely,
Zhuqing

**Comment by hannespetur** [comment]
1. Can you be more specific which variants are missed? Are they at least 50bp in size?
2. log file should go into a file called "log" using this command. Is there no such file?
3. Okay that is good, I have seen PASS_ratio to be a good metric to use for filtering.

Best,
Hannes
