### ISSUE TITLE
Increasing sensitivity for variants with limited read support

### ISSUE THREAD

**Issue by twesigomwedavid** [DecodeGenetics/graphtyper#46]
Hi Hannes,

I am running graphtyper genotype. However, there are some heterozygous variants being missed (compared with truth data) probably due to the alt allele depth being low (~10) compared to the ref allele depth (~98 or more). Is there an option I can use to promote sensitivity for such variants? 

Thanks

David.

**Comment by hannespetur** [comment]
Hello,

you might experiment with decreasing the values of the advanced options: `--genotype_aln_min_support --genotype_aln_min_support_ratio --genotype_dis_min_support --genotype_dis_min_support_ratio`. This will effect the amount of evidence is needed to add a variant to the graph. You should also set `--minimum_extract_score_over_homref=0`. However, there is no option to change the assumption of ~50% AF for heterozygous sites in the genotyping model and if the variant is not called it would be removed in the subsequent iteration. So I would only expect these change to catch variants with AF of at least 15%.

Best,
Hannes

**Comment by twesigomwedavid** [comment]
Hi Hannes

Thanks a lot that did the trick. I had experimented with reducing the values of the other advanced options but hadn't set `--minimum_extract_score_over_homref=0`. I am now able to call the variants with limited read support - they have been validated with Sanger sequencing etc already. Perhaps this is something the rest of the community can benefit from? 

Regards,
David.
