### ISSUE TITLE
LowQUAL for all homozygous reference sites

### ISSUE THREAD

**Issue by jjfarrell** [DecodeGenetics/graphtyper#47]
The VCF filter field is always assigned "LowQUAL" for all the homozygous reference variants larger than 50bp. Not one had a FILTER=PASS.
Here is an example. This was not an issue for the het or homozygous non-reference. 

```
chr1    21000   chr1:21000:DG   N       <DEL:SVSIZE=5000:AGGREGATED>    0       LowQUAL ABHet=-1;ABHom=1;AC=0;AF=0;AN=2;CR=0;END=26000;LOGF=0.07167;MaxAAS=0;MaxAASR=0;MaxAltPP=0;NHet=0;NHomAlt=0;NHomRef=1;PASS_AC=0;PASS_AN=2;PASS_ratio=1;QD=0;
RefLen=1;SB=0.2174;SBAlt=-1;SBF=10,0;SBF1=4,0;SBF2=6,0;SBR=36,0;SBR1=22,0;SBR2=14,0;SVLEN=5000;SVMODEL=AGGREGATED;SVSIZE=5000;SVTYPE=DEL;SV_ID=12;SeqDepth=46;VarType=DG        GT:FT:AD:MD:DP:RA:PP:GQ:PL      0/0:PASS:46,0:0:46:46,0:0:99:0,138,
255
chr1    21000   chr1:21000:DG.0 N       <DEL:SVSIZE=5000:BREAKPOINT>    0       LowQUAL ABHet=-1;ABHom=1;AC=0;AF=0;AN=2;CR=0;END=26000;LOGF=0.07167;MaxAAS=0;MaxAASR=0;MaxAltPP=0;NHet=0;NHomAlt=0;NHomRef=1;PASS_AC=0;PASS_AN=2;PASS_ratio=1;QD=0;
RefLen=1;SB=0.2174;SBAlt=-1;SBF=10,0;SBF1=4,0;SBF2=6,0;SBR=36,0;SBR1=22,0;SBR2=14,0;SVLEN=5000;SVMODEL=BREAKPOINT;SVSIZE=5000;SVTYPE=DEL;SV_ID=12;SeqDepth=46;VarType=DG        GT:FT:AD:MD:DP:RA:PP:GQ:PL      0/0:PASS:46,0:0:46:46,0:0:99:0,138,
255
chr1    21000   chr1:21000:DG.1 N       <DEL:SVSIZE=5000:COVERAGE>      0       LowABHom;LowQUAL        ABHet=-1;ABHom=0.7879;AC=0;AF=0;AN=2;CR=0;END=26000;LOGF=0.000571;MaxAAS=14;MaxAASR=0.2121;MaxAltPP=0;NHet=0;NHomAlt=0;NHomRef=1;PASS_AC=0;
PASS_AN=2;PASS_ratio=1;QD=0;RefLen=1;SB=0.2174;SBAlt=-1;SBF=10,0;SBF1=4,0;SBF2=6,0;SBR=36,0;SBR1=22,0;SBR2=14,0;SVLEN=5000;SVMODEL=COVERAGE;SVSIZE=5000;SVTYPE=DEL;SV_ID=12;SeqDepth=66;VarType=DG      GT:FT:AD:MD:DP:RA:PP:GQ:PL      0/0:PASS:52
,14:0:66:0,0:0:45:0,45,255


```

**Comment by hannespetur** [comment]
Hello, 

This looks like expected behavior to me unless I am missing something - the QUAL estimates how likely the alt. allele is present in the population and with zero carriers that likelihood should be low.

Best,
Hannes

**Comment by hannespetur** [comment]
Perhaps what you want is in FT format field, which would be "PASS" if graphtyper is confident in its call (including homozygous reference calls).

**Comment by jjfarrell** [comment]
QUAL should indicate if it is a high confident call (based on the  VCF Spec). This has a GQ of 45 which indicates it is a confident call.  QUAL is somewhat redundant with GQ when it is a single sample.   In a single sample vcf, graphtyper is assigning all 0/0 high quality calls (GQ >20) to LowQUAL which they are not.   So there is no distinction between a low coverage low quality call (DP <10 and GQ <20) and high coverage(DP >=10) and high GQ site (GQ>=20).  

VCF spec....
QUAL - quality: Phred-scaled quality score for the assertion made in ALT. i.e. −10log10 prob(call in ALT is
wrong). If ALT is ‘.’ (no variant) then this is −10log10 prob(variant), and if ALT is not ‘.’ this is −10log10
prob(no variant). High QUAL scores indicate high confidence calls. Although traditionally people use integer
phred scores, this field is permitted to be a floating point to enable higher resolution for low confidence calls if
desired. If unknown, the missing value should be specified. (Numeric)

FILTER - filter status: PASS if this position has passed all filters, i.e., a call is made at this position

**Comment by hannespetur** [comment]
Hmm, okay so our understanding of the specs is not quite the same. We should at least agree that the relevant formula is: `QUAL=-10log10 prob(no variant)`

If all calls are homozygous reference calls then we found no evidence that there is a variant there and `prob(no variant)~=1`. This would mean `QUAL~=0` based on the formula.

Best,
Hannes

**Comment by jjfarrell** [comment]
What is the pred quality score that this site is homozygous reference? Isn't it 45 not 0?

Otherwise no homozygous reference sites will have FILTER="PASS" under the present interpretation. The PASS is to indicate the site is suitable for analysis not that there is a ALT allele there.  This site has a high quality GT based on the GQ.

**Comment by hannespetur** [comment]
> Is there another metric that is setting the filter to LowQUAL other than GQ.

The LowQUAL filter is determined by QUAL and only QUAL. GQ is not used for this purpose.

> Presently all homozygous reference sites have FILTER="PASS" with graphtyper.

What? No.

> The PASS is to indicate the site is suitable for analysis not that there is a ALT allele there. This site has a high quality GT based on the GQ. Doesn't this indicate that there is high confidence that it is 0/0 reference. So why should it be filtered?

Yes, high GQ indicates that there is high confidence in the genotype call. Variants with only homozygous reference calls are frequently omitted from downstream analysis. Internally, we are utilizing all of the available filters in graphtyper. But these filters are just flags, you are free to decide which filter(s) are suitable for your analysis, if any.


Best,
Hannes
