### ISSUE TITLE
How to realign short reads to the graph pan-genome (constructed by GraphTyper construct) ?

### ISSUE THREAD

**Issue by caixu0518** [DecodeGenetics/graphtyper#51]
Hello graphtyper team,

I want to use graphtyper to genotype SVs (detected by assemblies aligments) in a large population (350 accessions, short reads). I can use construct subcommand to construct graph pangenome, however, there is no subcommnad to map all short reads to the graph pangenome to obtain the bam files. Thank you in advance for your response.

Best.
Xu

**Comment by hannespetur** [comment]
Hello,

Sorry, it is not possible to obtain a bam file containing the graph alignments - graphtyper will only update genotype likelihood score based on graph realignments but does not output the realignments.


Best,
Hannes

**Comment by ekg** [comment]
This is specifically something you can do with vg map. It can be made to emit a BAM file representing the alignments relative to the reference path. This BAM could in principle be used in graphtyper.
