### ISSUE TITLE
Error while loading some BAM indexes

### ISSUE THREAD

**Issue by twesigomwedavid** [DecodeGenetics/graphtyper#53]
@hannespetur Graphtyper is throwing an error for BAM files that have indexes named as file.bai. See example below;

input files: `file.bam, file.bai` - instead of `file.bam, file.bam.bai`

```
$ graphtyper genotype reference.fasta --sam=file.bam --region=<value> --output=test
$ Could not load local index file 'file.bam.bai'
<error> bamshrink.cpp:713 Could not read index file file.bam.bai
```

Is it possible to include support for such BAM/index pairs as some groups do name their indexes using that system i.e. `file.bai`? 

Thanks

David.

**Comment by hannespetur** [comment]
Hello,

you could use the `--sams_index` option which expects a file containing the path to the index file (one per line). They must be given in the same order as the input BAM/CRAM files if you input multiple files.

```sh
$ graphtyper genotype reference.fasta --sam=file.bam --sams_index=<(echo file.bai) --region=<value> --output=test
```

Best,
Hannes

**Comment by twesigomwedavid** [comment]
Hi Hannes,

Okay great. Thank you.

David
