### ISSUE TITLE
SV end points for "OG" variants

### ISSUE THREAD

**Issue by MaximilianStammnitz** [DecodeGenetics/graphtyper#54]
Hi @hannespetur,

Thanks again for fixing [#43](https://github.com/DecodeGenetics/graphtyper/issues/43)!

Browsing through my first VCFs, I found five variant classes ("VarType"): OG (very long/interchromosomal), UG (duplications), DG (deletions), FG (insertions), XG (complex indels?). For OG-type variants, I consistently obtain REF allele counts only (i.e. ABHet=-1;ABHom=1). This was very unexpected because some of these calls are definitely true heterozygotes.

So I dipped into the VCF's INFO field a bit more, and realise that for OGs the specified SV "END" point is actually the same as the "POS" identifier in column 2. This is not the case for the other two potential long-range VarTypes UG and DG. If this "END" point is indicative of GraphTyper's internal use, then to me it feels like the script might currently "go circular" for OGs, checking starting point <> starting point combinations which therefore nearly always render 100 % REF.

Could you please have a look at this? Happy to test any changes to this again.

Best,
Max

**Comment by hannespetur** [comment]
Hey, I don't think the END point is indicative to what's happening internally, the "target" site of the breakend has no effect on the END position. Probably the END should not be reported or be set as missing (".") in this case.

Our breakpoint genotyping is quite strict meaning that if the breakend begin or target position is inaccurate by just 1bp this would likely result in a ref call. Is it possible that these true heterozygous breakends just are slightly inaccurate in the input VCF?


Best,
Hannes

**Comment by MaximilianStammnitz** [comment]
Okay, that's good to know regarding the "END" INFO field. So the OG issue must lie somewhere else then.

I'd assume that the Manta -> svimmer merged input VCF breakpoint accuracies should equally affect UG, DG, FG, XG calls. However, these are rendering (mostly very confident) HET calls in the right samples. So I still expect that there's something odd specifically with the OG implementation. Maybe it's easiest if I forward you a toy example?

**Comment by hannespetur** [comment]
Yes sure, thank you. You can mail me at hannese<at>decode.is

Best,
Hannes

**Comment by MaximilianStammnitz** [comment]
Hi Hannes,

While preparing the toy set, I just realised that part of the problem may likely be related to [#23](https://github.com/DecodeGenetics/graphtyper/issues/23) about the new Manta 1.6 inversion format. The developers have supplied a [script](https://github.com/Illumina/manta/blob/27ba65e788572abb2b3d8afcb6aea1f5e8e98ae6/src/python/libexec/convertInversion.py) to re-convert "BND" style inversions back the old format, but at least in my case this doesn't work as cleanly as hoped.

Will retest my particular examples using Manta 1.5.1 first, and get back to you again later.

**Comment by MaximilianStammnitz** [comment]
Update for this today:
1. Intrachromosomal inversions can indeed be genotyped by [fixing the merged "INV" inputs from svimmer](https://github.com/DecodeGenetics/svimmer/pull/5). These calls turn from OG into TG in the GraphTyper output.
2. Interchromosomal variants don't work yet, maybe also because of the input specifics "MantaBND". Shortly forwarding you the toy with a high-confidence interchromosomal SV, would be great to also clear this up.
