### ISSUE TITLE
Applying variants with symbolic alleles made by genotype_sv

### ISSUE THREAD

**Issue by bricoletc** [DecodeGenetics/graphtyper#61]
Hi!

I'm using `graphtyper genotype_sv` for genotyping deletions together with SNPs/indels, and then applying the genotyped variants to the ref genome using

```
samtools faidx ref:start-stop ref.fasta | bcftools consensus genotype_sv_out.vcf.gz
``` 
And `bcftools` errors on a genotyped deletion on a toy example with `Symbolic alleles other than <DEL> are currently not supported: <DEL:SVSIZE=2304:AGGREGATED>`

The deletion in question has three records, all with same POS, ref of `N` and successively as ALT: `<DEL:SVSIZE=2304:AGGREGATED>, <DEL:SVSIZE=2304:BREAKPOINT>, <DEL:SVSIZE=2304:COVERAGE>`

i) Have you ever run into such an application (applying variants from genotype_sv), and if so how do you deal with such cases?
ii) I noticed replacing the above `<DEL:SVSIZE=2304:AGGREGATED>` with `<DEL>` restores bcftools's ability to apply the deletion to the ref sequence. I'm considering doing that as a hack?

Best

**Comment by bricoletc** [comment]
By the way: 
* bcftools version 1.10.2 (current latest)
* graphtyper version 2.5.1 (also latest)

**Comment by hannespetur** [comment]
Hello, (i) no, I haven't been applying SVs back to the reference sequence (ii) Yes, I can't think of anything else simpler than replacing `<DEL:SVSIZE=2304:AGGREGATED>` with `<DEL>`, but this workaround will not work for other SV types.


Best,
Hannes

**Comment by bricoletc** [comment]
Hi Hannes, thanks for reply, doing that works.
I noticed that a DEL has three records associated to it. Could you explain why that's the case?

(I've had to keep only one per deletion so that bcftools doesn't complain about overlapping calls)

**Comment by hannespetur** [comment]
Hey, basically there are a few genotyping models for each type of SV. The aggregated model is the main one and usually performs best, but the output of the other models are also printed in the output for completeness and debugging.

Best,
Hannes

**Comment by bricoletc** [comment]
Great! This issue is good to close for me. Thanks.
