### ISSUE TITLE
Hello, I don't think it should need that much, less than 4GB per thread should be enough for 350 samples (assuming 30x coverage).

### ISSUE THREAD

**Issue by koujiaodahan** [DecodeGenetics/graphtyper#62]
Hello, I don't think it should need that much, less than 4GB per thread should be enough for 350 samples (assuming 30x coverage).

For me I typically get "Killed" message if it failed on memory though. Could you rerun with `--verbose` (or even `--vverbose`) to get a better idea where in the process it is failing.

Best,
Hannes

_Originally posted by @hannespetur in https://github.com/DecodeGenetics/graphtyper/issues/58#issuecomment-674789266_

**Comment by hannespetur** [comment]
I have replied on the other issue.

Best, Hannes
