### ISSUE TITLE
Genotyping SNPs that are non-variable within dataset

### ISSUE THREAD

**Issue by malmarri** [DecodeGenetics/graphtyper#66]
Hi,

I am using graphtyper to genotype a specific list of SNPs supplied as a VCF (--vcf=) using the genotype option in about 100 samples.

I noticed that not all SNPs that are within the supplied VCFs are genotyped. If the position is not variable within the samples being genotyped, does graphtyper output such a site in the multi-sample VCF? (i.e. non-variable, all SNVs genotype ref/ref).

Thanks

**Comment by hannespetur** [comment]
Hello, yes if all genotypes are ref/ref the variant is not in the final output. I could quite easily add an argument option to output such variants along with variable sites, would you like me to do that or are you only wondering if the behavior you are seeing is normal?

Best,
Hannes

**Comment by malmarri** [comment]
Thanks for the quick reply.

I am concerned that this behaviour would result in reference bias. If, due to stochastic reasons in a sample, a region is at a lower depth (or even zero depth) than the average, then the variant would not be identified and be set as reference (It could have been a alternative het for e.g.). This would particularly affect calling in smaller sample sizes at rarer variants (singletons etc.) Adding an argument to output these sites would be greatly appreciated.

Best wishes,
Mo

**Comment by 23andme-jaredo** [comment]
This functionality would also be very useful for emulating genotype microarray data in imputation experiments (as another example).

**Comment by hannespetur** [comment]
Added in version v2.6.1 you can change the behaviour by using the option `--force_no_filter_zero_qual` in the genotype subcommand. The option is marked advanced so its help page only appears if you do `graphtyper genotype -a --help`.

**Comment by malmarri** [comment]
Thanks!

**Comment by 23andme-jaredo** [comment]
Amazing! Thanks @hannespetur.
