### ISSUE TITLE
Genotyping both Indels and SVs

### ISSUE THREAD

**Issue by jjfarrell** [DecodeGenetics/graphtyper#69]
Is it possible to genotype indels and SVs with one run? Or should a vcf with both indels (<50bp) and SV (>=50b) be split into 2 vcfs and run separately with genotype and genotype_sv respectively.   The graphtyper_sv will output  genotype indels in the vcf provided that look like the graphtyper output.  Is the graphtyper model automatically being used instead of graphtyper_sv for the indel sites <50bp?

**Comment by hannespetur** [comment]
Hey, yes with an input VCF containing both small variants and SVs you should be able to run "genotype_sv" on the whole VCF. There won't be any new variants discovered and the variants smaller than 50bp using the same model as in "genotype". There are a few slight differences in preprocessing between the two subcomands (input read filtering, graph size) so the results won't be the exact same as doing two runs with a split VCF, but highly similar.

Best,
Hannes

**Comment by jjfarrell** [comment]
Thanks! May be a useful detail to add to the documentation.
