### ISSUE TITLE
Binary of graphtyper runs extremely slow

### ISSUE THREAD

**Issue by shangshanzhizhe** [DecodeGenetics/graphtyper#88]
Hi,

Thank you for the useful tool. I failed when compiling the graphtyper locally, so I downloaded the binary file of it. But when I tried to genotype SVs across about 50 samples with multithreads, it seems that it was not using ideal cpus and memories as expected. The process was very slow. Do you have any suggestions on this?

All the best,
Shangzhe

**Comment by hannespetur** [comment]
Hello, have you seen this section in our user guide: https://github.com/DecodeGenetics/graphtyper/wiki/User-guide#subsampling-reads-in-abnormally-high-sequence-depth

Maybe graphtyper is very slow in some regions where the sequence depth is extremely high (10,000x+), but we provide a way to subsample the reads from such regions to make graphtyper run much faster.


Best,
Hannes

**Comment by shangshanzhizhe** [comment]
Hi,
Thanks for your remind. My hard disk was mapped to the nodes by net and the I/O was crowded. I moved the data files to a  physically mounted disk and graphtyper worked greatly. Thanks for the awesome tool again!

Shangzhe
